# Generated by Django 4.2.16 on 2024-10-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_userprofile_taxpayerprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='business_type',
            new_name='business_registration_number',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='taxpayer_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
