# Generated by Django 4.2.16 on 2024-10-03 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0003_rename_business_type_userprofile_business_registration_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxpayerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='taxtype',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='business_documents',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='system_generated_id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='business_registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='income_range',
            field=models.CharField(blank=True, default='Unspecified', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TaxpayerProfile',
        ),
        migrations.AddField(
            model_name='taxinvoice',
            name='bill_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tax.billtype'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='taxpayer_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tax.taxpayercategory'),
        ),
    ]
