# Generated by Django 4.2.16 on 2024-09-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_company_user_company_address_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('auditor', 'Auditor'), ('taxpayer', 'Taxpayer')], default='taxpayer', max_length=10),
        ),
    ]
